name       : haskell-lukko
version    : 0.1.1.3
release    : 1
source     :
    # Revision 4
    - https://hackage.haskell.org/package/lukko-0.1.1.3/lukko-0.1.1.3.tar.gz : a80efb60cfa3dae18682c01980d76d5f7e413e191cd186992e1bf7388d48ab1f
license    : GPL-2.0-or-later
component  : programming.haskell
summary    : File locking for Haskell
description: |
    lukko provides access to platform dependent file locking APIs.
builddeps  :
    - ghc-devel
setup      : |
    cp $pkgfiles/4.cabal lukko.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
